services:
  - type: web
    name: portfolio-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: mydevprojects.onrender.com
      - key: EMAIL_HOST_USER
        value: usamaibrahim737@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
