services:
  - type: web
    name: app
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: portpolio.onrender.com
      - key: EMAIL_HOST_USER
        value: usamaibrahim737@gmail.com
